[project]
name = "dt-anti-sanction"
version = "1.3"
description = "A Windows utility to quickly change DNS settings for bypassing restrictions."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
